[ActiveSupport PAR]
; # of global secondary clocks
GLOBAL_SECONDARY_USED = 0;
; I/O Bank 0 Usage
BANK_0_USED = 0;
BANK_0_AVAIL = 14;
BANK_0_VCCIO = NA;
BANK_0_VREF1 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 0;
BANK_1_AVAIL = 14;
BANK_1_VCCIO = NA;
BANK_1_VREF1 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 2;
BANK_2_AVAIL = 14;
BANK_2_VCCIO = 3.3V;
BANK_2_VREF1 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 10;
BANK_3_AVAIL = 14;
BANK_3_VCCIO = 3.3V;
BANK_3_VREF1 = NA;
